project:
  type: website
  output-dir: _site

website:
  title: "Hyuk-soo Kwon"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: presentations.qmd
        text: Presentations
      - href: teaching.qmd
        text: Teaching
  page-footer:
    center: "© Hyuk-soo Kwon"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true

execute:
  freeze: auto
